
apiVersion: v1
kind: Namespace
metadata:
  name: return-hostname

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: return-hostname-deployment
  namespace: return-hostname
  labels:
    app: return-hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: return-hostname
  template:
    metadata:
      labels:
        app: return-hostname
    spec:
      containers:
      - name: return-hostname
        image: dkoterlan/return-hostname-express:1.0.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: return-hostname-loadbalancer
  namespace: return-hostname
spec:
  type: LoadBalancer
  selector:
    app: return-hostname
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080